services:
  api:
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g

  worker:
    restart: always
    deploy:
      resources:
        limits:
          memory: 8g

  db:
    ports: []
